const PATH = "/run/media/ashedko/_data_/datasets/UNC/"
const PATH_Fmt = x -> PATH * string(x) * "/"
const NSUBJ = 29 # 7 in test runs
const SIZEX = 91
const SIZEY = 109
const SIZEZ = 91
const SHAPE = (SIZEX,SIZEY,SIZEZ)
const SIZE = SIZEX * SIZEY * SIZEZ
const LEN = 3620
const NEXP = 91
